import type { CaseStatus } from "@/types";

export const CASE_STATUS_TRANSITIONS: Record<CaseStatus, readonly CaseStatus[]> = {
  TRIAGEM: ["COLETANDO_INFORMACOES", "REVISAO_HUMANA"],
  COLETANDO_INFORMACOES: ["AGUARDANDO_INFORMACOES", "COLETANDO_EVIDENCIAS", "NECESSITA_ESCLARECIMENTO", "REVISAO_HUMANA"],
  AGUARDANDO_INFORMACOES: ["COLETANDO_INFORMACOES", "COLETANDO_EVIDENCIAS", "REVISAO_HUMANA"],
  COLETANDO_EVIDENCIAS: ["ANALISANDO", "NECESSITA_ESCLARECIMENTO", "REVISAO_HUMANA"],
  ANALISANDO: ["NECESSITA_ESCLARECIMENTO", "PREPARANDO_MINUTA", "REVISAO_HUMANA"],
  NECESSITA_ESCLARECIMENTO: ["COLETANDO_INFORMACOES", "COLETANDO_EVIDENCIAS", "ANALISANDO", "REVISAO_HUMANA"],
  PREPARANDO_MINUTA: ["AGUARDANDO_REVISAO", "REVISAO_HUMANA"],
  AGUARDANDO_REVISAO: ["AJUSTANDO_MINUTA", "MINUTA_APROVADA", "REVISAO_HUMANA"],
  AJUSTANDO_MINUTA: ["AGUARDANDO_REVISAO", "REVISAO_HUMANA"],
  MINUTA_APROVADA: ["PRONTO_PARA_PROTOCOLO", "REVISAO_HUMANA"],
  REVISAO_HUMANA: ["ENCAMINHADO_ADVOGADO"],
  ENCAMINHADO_ADVOGADO: ["AGUARDANDO_REVISAO", "EM_ANDAMENTO"],
  PRONTO_PARA_PROTOCOLO: ["EM_ANDAMENTO", "CONCLUIDO"],
  EM_ANDAMENTO: ["CONCLUIDO"],
  CONCLUIDO: [],
};

export function canTransitionCaseStatus(from: CaseStatus, to: CaseStatus): boolean {
  return from === to || CASE_STATUS_TRANSITIONS[from].includes(to);
}

export function assertCaseStatusTransition(from: CaseStatus, to: CaseStatus): void {
  if (!canTransitionCaseStatus(from, to)) {
    throw new Error(`Transição de status não permitida: ${from} → ${to}`);
  }
}
